# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: 'tim61114.github.io'
description: "Welcome to my homepage"
# abaseurl: "/tim61114.github.io"
url: "https://www.tim61114.github.io"

header_pages:
  - index.md
  - about.md
  - projects.md
  # - peter.md
  - contact.md

footer: 'Page modified by tim61114 / Check out my <a href="https://github.com/tim61114" target="_blank">github</a>  / Check out this <a href="https://github.com/b2a3e8/jekyll-theme-console" target="_blank">jekyll theme </a>'

# style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

remote_theme: b2a3e8/jekyll-theme-console
